title: xImAnton.de
email: anton@ximanton.de
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ximanton.de" # the base hostname & protocol for your site, e.g. http://example.com
github_username: "xImAnton"
discord_tag: "xImAnton_#2013"
instagram: "antondevde"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/projects/:num"
permalink: "/projects/:year-:month-:day/:title"
imprint: false

exclude: [ Gemfile, Gemfile.lock, Makefile, ximanton.gemspec ]
include:
  - _pages
