title: xImAnton.de
email: anton@ximanton.de
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ximanton.de" # the base hostname & protocol for your site, e.g. http://example.com
github_username: "xImAnton"
discord_tag: "xImAnton_#2013"
instagram: "antondevde"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate

include:
  - _pages

paginate: 5
paginate_path: "/projects/:num"
permalink: "/projects/:year-:month-:day/:title"

exclude: [ Gemfile, Gemfile.lock, Makefile, ximanton.gemspec ]
